Ti backend
nymea/nymea-zigbee pull request #33
Opened 2022-01-30 12:54 UTC by mzanetti

2022-03-02 13:37 UTC, t-mon requested changes

2022-03-02 16:49 UTC, mzanetti commented on libnymea-zigbee/backends/ti/zigbeebridgecontrollerti.cpp
> +        {
That's the payload of the ExtNwkInfo response...

2022-03-02 18:12 UTC, mzanetti commented on libnymea-zigbee/backends/ti/interface/zigbeeinterfaceti.cpp
> +    m_serialPort->setFlowControl(QSerialPort::NoFlowControl);
The RTS/DTR calls are not actually really used for transmission:

While CC2530/CC2531 models just need a "magic byte" of 0xEF to skip the bootloader, the CC2652/CC1352 chipsets seem to require to set and unset RTS in order to make the bootloader proceed... That's really the only time RTS is used. 

The transmission itself doesn't use flow control but every packet starts with a "start of frame" byte 0xFE on which the communication syncs up.

2022-03-02 18:14 UTC, mzanetti commented on libnymea-zigbee/backends/ti/interface/zigbeeinterfaceti.cpp
> +    m_reconnectTimer = new QTimer(this);
ok... added that. To be honest I didn't try it with such old Qt versions but I do remember this as well being an issue back then.

2022-03-07 14:34 UTC, t-mon approved these changes

2022-03-29 10:28 UTC, merged